### PR TITLE
Pulling beta 7 changes to the West Rail PIDS branch

### PR DESCRIPTION
**Pull request by jonafanho**

### CODE REVIEW

**Comment by jonafanho** [comment]
Changes are too complex, sorry. It would be easier to write it again from scratch.

**Comment by Kenny-Hui** [comment]
So is it just too complex to merge/catch up all the commits, or the code itself is too complex?

Either way I'll see what I can do when I got time

**Comment by jonafanho** [comment]
Actually, if you look at the network graph, it seems like this is just an old fork of a merged branch so I don't think I need to merge it again.

**Comment by Kenny-Hui** [comment]
So do I need to do anything with this?
Sorry, not familiar with how PR works here (Normally I juat create my branch, work on it, then request to merge to the latest code)

**Comment by jonafanho** [comment]
Yeah I don't think there's anything you need to do. Good work on the ticket machines, I merged that in today!

**Comment by Kenny-Hui** [comment]
Still not sure what is this suppose to mean, it's merged into a new branch called "west-rail-pids"

Then this is suppose to pull all the latest change to the "west-rail-pids" branch, but is closed so changes were not made. 

Then the branch just disappears? I don't see any indication of the code being merged to the "beta-7" branch

**Comment by jonafanho** [comment]
It's not merged because the pull request is closed. The code is too out of date so there were too many merge conflicts.

**Comment by Kenny-Hui** [comment]
So if the West Rail PIDS has to be implemented, does that mean I have to rewrite it again on the latest commit?

**Comment by jonafanho** [comment]
Unfortunately yes, sorry about that. The depot update changed a lot of the PIDS mechanics, so it might need to be rewritten.

**Pull request closed without merging**
