### PR TITLE
The Train that people wanted

### PR DESCRIPTION
**Pull request by Eric28020**
Ready to merge

Notes: The following issue that needs to be closed right away is #201. Also according to the [Gradle 7.4.2 release notes](https://docs.gradle.org/7.4.2/release-notes.html), I have to update Gradle to 7.4.2 just in case.

### CODE REVIEW

**Comment by Ultimate-USA-YT** [comment]
Yes! Q Train!

**Comment by Ultimate-USA-YT** [comment]
Yes! We got the Silverliner!

**Comment by kettle-7** [comment]
> Yes! We got the Silverliner!

nah that was only you that wanted that

**Comment by kettle-7** [comment]
it's between P and S in the alphabet

**Comment by DumbSharkGura** [comment]
Uhhhhhhhh
I highly suggest you might need to revise the textures NGL, since I don't think that the textures are kinda decent for publishing to the main mod.

**Comment by DumbSharkGura** [comment]
Plus for the Q-Train, I highly suggest like not to rush that rn, since I'd rather wait for it to like actually debut, so that we can get more accurate photos for reference in the models and textures.

**Comment by jonafanho** [comment]
I will close this for now since #355 is merged. Feel free to open another pull request when the Q-Train is ready. Thanks!

**Pull request closed without merging**
