### PR TITLE
Longer train frequency and Menu Change

### PR DESCRIPTION
**Pull request by ExtremeMakerX**
This basically makes the Slider longer, 
4x the range of motion of the slider and changes the 20s to 5s tph. Also changes the depot menu.

Screenshots!

### CODE REVIEW

**Comment by jonafanho** [comment]
I think we might want the timetable to have more options for lower frequencies, not the other way around. Good concept, though.

**Comment by linuxkettle** [comment]
I'm all for it! Plus, if you want for example a train every six hours then you change every sixth slider to 1tph.

**Comment by linuxkettle** [comment]
It would be nice to have 60s and 120s options though.

**Comment by ExtremeMakerX** [comment]
Yeah for sure it be interesting but it would have been better if the signaling system was implementing

**Pull request closed without merging**
