### PR TITLE
Support 22.5 degrees increments

### PR DESCRIPTION
**Pull request by Simba98**
- Totally rewrite the rail parameter calculating function, support for any angles
- Support 22.5 degree increments, 0/22.5/45/67.5/90/112.5/135/157.5.
- Incompatible with old versions

### CODE REVIEW

**Comment by Simba98** [comment]
image

**Comment by Simba98** [comment]
image

**Comment by kettle-7** [comment]
Congrats on making world's bluest spaghetti :D

**Comment by kettle-7** [comment]
Any idea on how s-curve with 22.5° difference works? Out of curiosity, it fascinates me all these orientations.

**Comment by Simba98** [comment]
> Any idea on how s-curve with 22.5° difference works? Out of curiosity, it fascinates me all these orientations.

Just Geometry in middle school, only use up to two arcs or one segment with one arc to connect them.
Nothing more than Geometry, 2D-Vector in middle school.

**Comment by kettle-7** [comment]
I meant how to tell between s curve and acute curve

**Comment by kettle-7** [comment]
but maybe just do s curve if the two rail nodes are the same direction facing

**Comment by YPetremann** [comment]
I got the same problem when making 45° turn implementation

**Comment by YPetremann** [comment]
Just as we talked about it, before releasing we should try to find how to migrate old rails nodes to new implementation.

**Comment by cherbert** [comment]
How much begging do I have to do for you to hide some code that I can unlock to have track use an entity model?

**Comment by Simba98** [comment]
> Just as we talked about it, before releasing we should try to find how to migrate old rails nodes to new implementation.

As yesterday you mentioned, the update series function provided by fabric is a good choice, Let's work  for that.

**Comment by jonafanho** [comment]
I'm working on backwards compatibility as part of the merge to the main code. Thank you so much for your work; I'm really excited!

**Comment by Simba98** [comment]
> I'm working on backwards compatibility as part of the merge to the main code. Thank you so much for your work; I'm really excited!

Also, please be reminded that check the TODOs in RenderSignalBase.java. 

The TODOs in Rail.java is for supporting very weird rail connections, so they can be ignored.
Two TODOs in RenderSignalBase.java may need you to check them very carefully, I didn't understand them well, just change them based on the function name.

**Pull request merged**
