### PR TITLE
Locking PSD and APG by LX86

### PR DESCRIPTION
**Pull request by jonafanho**

### CODE REVIEW

**Comment by Kenny-Hui** [comment]
Might've been a terrible mistake using blockstates...
I think I've doubled the blockstates APG/PSD has, so presumably it's around 256 states?

I've also noticed a significant increase in loading time, from 1m05s to 1m40s at the latest commit.
Not sure what could be done at this point, I didn't pay attention to this when developing

**Comment by jonafanho** [comment]
Yes, adding an extra boolean field essentially doubled the blockstates. I wouldn't worry too much about it, since it's just increased loading time but not laggy in-game.

**Comment by jonafanho** [comment]
Now that I think about it, `open` shouldn't be a blockstate. It should probably be a tile entity (like my 1.10.2 versions of the mod) and render the door position using a tile entity renderer. I originally thought this would lag up the world a lot of you have too many tile entities at a platform, but it's actually not noticeable and it could make the doors move smoother.

**Comment by Kenny-Hui** [comment]
That would probably be ideal
I think each APG/PSD doors adds around 10-15 second of load time, if someone is to add more APG it would clog up the load time significantly. (The hundreds of PSD door is also a bit tough to work with, even though it's programmatically generated)

**Pull request merged**
