### PR TITLE
Inventory Filters

### PR DESCRIPTION
**Pull request by ZiYueCommentary**
Adding some beautiful filters for MTR tabs.
image

### CODE REVIEW

**Comment by ajh123** [comment]
It's like those Mr Crayfish ones! Being for Fabric as well makes them even better!

**Comment by ZiYueCommentary** [comment]
> It's like those Mr Crayfish ones! Being for Fabric as well makes them even better!

These icons were taken from mrcrayfish's, but the mechanism is different.

**Comment by jonafanho** [comment]
Sorry closed this on accident. Is this compatible with both Forge and Fabric?

**Comment by ZiYueCommentary** [comment]
> Sorry closed this on accident. Is this compatible with both Forge and Fabric?

It is both compatible, I also update this feature to make it compatible with 3.2.0

**Pull request closed without merging**
