### PR TITLE
[Pending Train Model Review] Q-train

### PR DESCRIPTION
**Pull request by Eric28020**
Ready to merge.
Note: According to the [Gradle Release Notes](https://docs.gradle.org/7.5.1/release-notes.html), I have to update Gradle to 7.5.1.

### CODE REVIEW

**Comment by Ultimate-USA-YT** [comment]
Woohoo!

**Comment by XHG78999** [comment]
People doesn't like this. https://www.mtrbbs.top/forum.php?mod=viewthread&tid=139&extra=

**Comment by Eric28020** [comment]
Usually Done is better than Perfect.

**Comment by DumbSharkGura** [comment]
You know people prefer quality than quantity right? Not everyone wants trains that are made under speedrun without decent and promising quality.
Plus if it is okay to merge this PR wouldn't be left opened and untouched that long.

**Comment by kettle-7** [comment]
> Usually, Done is better than Perfect.

not really

**Comment by DumbSharkGura** [comment]
As far as I'm aware, you took photos from Nanyue Express's unfinished photo at [https://www.facebook.com/railwaydrawings/photos/a.405149476274831/2950280055095081/](url)
However, I have to remind you that Nanyue Express strictly forbids anyone using their artwork according to many pasts experiences. Using their photo without even asking is somewhat considered not respectful to them as this is not simply a "Google Photo", plus will push MTR Mod to controversy and drama beyond the MTR Mod community like the whole Hong Kong railfan community base (as there have been history of mass scolding against the ones stealing the pics of them before) which is unwanted and would cause potential chaos.

**Comment by Ultimate-USA-YT** [comment]
This could Re-Emerge as the Train is in Service AFAIK

**Pull request closed without merging**
