### PR TITLE
acceleration

### PR DESCRIPTION
**Pull request by zrll12**
add dynamic acceleration.
Now trains will accelerate smoother(and slower), just like real ones

### CODE REVIEW

**Comment by kettle-7** [comment]
Somebody has attempted this but it is a breaking change, unless it can be configured in depot / siding settings it will affect people who have relied on the current acceleration speed for some things.

**Comment by kettle-7** [comment]
The way you have done it however... It would definitely now be easier to implement a setting for how fast they accelerate.

And I must admit this does look very nice in game.

**Comment by zrll12** [comment]
Format of the acceleration description string is:
[[endSpeed1, acceleration1], [endSpeed2, acceleration2], [endSpeed3, acceleration3]]
the train will accelerate with accelerate1 between 0 and endSpeed1
the train will accelerate with accelerate2 between endSpeed1 and endSpeed2
endSpeed3 could be any number as the mod will accelerate at the last acceleration listed when current speed is out of this form.
By the way, I know the unit of speed is m/tick, but I'm currently not sure the unit of acceleration, so can anyone tell me what is the unit of acceleration in this mod?

**Comment by zrll12** [comment]
I have finished the website and the config screen so players can generate them on the website and put them in game.

**Comment by zrll12** [comment]
This is finally ready to be merged.

**Comment by kettle-7** [comment]
oh nice

works on server?

**Comment by zrll12** [comment]
YES!! It works on both side!

**Comment by zrll12** [comment]
Yes. It works on both side.

**Pull request closed without merging**
