### PR TITLE
Custom Rail Connector

### PR DESCRIPTION
**Pull request by yo56789**
Adds an Item, the Custom Rail Connector. It functions the same as all other rails but has a key-bind to open a screen that allows for the customization of its speed and if it is one way. The screen can only be opened if you are holding the item and the speed can be any number between 1 and 300.

### CODE REVIEW

**Comment by kettle-7** [comment]
jona will love the 999kph :~)

**Comment by ShimajiroOTS** [comment]
I don't know if there is a server that can withstand 999km/h, but I am very grateful that I can adjust the speed at any speed in 1km/h increments.

It seems that it can be set at a halfway speed, such as 55km/h or 70km/h.

**Comment by yo56789** [comment]
I’ll see if I can change the filter to limit the speed at 300.

**Comment by kettle-7** [comment]
*sad jonathan*

**Comment by saleem0915** [comment]
> I’ll see if I can change the filter to limit the speed at 300.
I kind of feel like the max speed should be higher

**Comment by yo56789** [comment]
> I’ll see if I can change the filter to limit the speed at 300.
> I kind of feel like the max speed should be higher


I don’t see the need for trains to go over 300. And it will probably start causing issues if it is any higher.

**Comment by yo56789** [comment]
Will have to open a new pr because in the process of trying to update the branch i seem to have broken a lot.

**Comment by sociqwq1** [comment]
> > I’ll see if I can change the filter to limit the speed at 300.
> > I kind of feel like the max speed should be higher
> 
> I don’t see the need for trains to go over 300. And it will probably start causing issues if it is higher.

But in China，the fastest train speed can reach 350 KM/H……

**Comment by kettle-7** [comment]
Yes and aeroplanes have gone faster than 3500kph, but you'd need a nasa supercomputer to be able to handle that, so where do you draw the line ?

**Comment by kettle-7** [comment]
Plenty of people already complain about the server lag that you get at 300kph, and sometimes even 200

**Comment by sociqwq1** [comment]
> Plenty of people already complain about the server lag that you get at 300kph, and sometimes even 200

對啊

**Pull request closed without merging**
