### PR TITLE
Real Time Scheduling

### PR DESCRIPTION
**Pull request by jonafanho**

### CODE REVIEW

**Comment by kettle-7** [comment]
How does it work in servers? Are the dashboard settings synced? And are there more frequent frequency settings to allow the trains to still run frequently when it's in real time mode?

**Comment by kettle-7** [comment]
I ask too many questions

**Comment by jonafanho** [comment]
All timestamps configured in the dashboard will be converted to local time zones. For example, if I am in Seattle and I set the train to depart at 07:10:00, someone in Hong Kong can open the dashboard and see that the train departs at 22:10:00. You can also type in `07:10:00 + 10*00:10:00`, which means the train will depart at 7:10 am along with ten more departures every 10 minutes. You may download the latest build on GitHub actions to try it out.

**Comment by kettle-7** [comment]
Oh this is amazing, can't wait for the preview!

**Pull request merged**
