### PR TITLE
[WIP] Implement Companies (station, route, depot claiming) and waterways on web map

### PR DESCRIPTION
**Pull request by ajh123**
This will implement #496. Please read that to understand what this will do.

### CODE REVIEW

**Comment by jonafanho** [comment]
Thanks! Please fork from the current development branch next time (3.2.0).

**Comment by Ultimate-USA-YT** [comment]
Can 1 Player have Multiple Companies?

**Comment by ajh123** [comment]
@Ultimate-USA-YT Not yet but it is technically possible because each company has its owner assigned to it. This also means a company may have multiple owners or a company could be "transferred" to a new owner.

**Comment by ajh123** [comment]
Might as well just close this now, because this is a bit messy and I've stopped working on it.
You may carry on the work if you want.

**Pull request closed without merging**
