### PR TITLE
More variety of rail speeds (60 km/h, 200 km/h), (Low acceleration will not be implemented to update)

### PR DESCRIPTION
**Pull request by BDark000**
- ~~Train accelerations decreased from 0.01m tick^-2 (4 m s^-2) to 0.004m tick^-2 (1.6 m s^-2), replay mod viewer seems buggy but not tested with exporting yet~~ 

- Added 60 km/h Emerald Rail Connector (item png not done yet)
- Added ~~100~~200 km/h Quartz Rail Connector (item png not done yet)
- ~~Changed the speed limit of Obsidian Rail Connector from 120 km/h to 130 km/h (item png not changed yet)~~
- ~~Changed the speed limit of Blaze Rail Connector from 160 km/h to 200 km/h (item png not changed yet)~~

### CODE REVIEW

**Comment by Kenny-Hui** [comment]
The 60km/h and 100km/h is a great addition, but you don't simply modify existing mod behavior for your own convenience.
There are other railway network out there who are designed to run on 160km/h, or 120km/h with this high acceleration rate.

You're just requesting at least over 80,000 people who downloaded this mod to rework their railway system because "You want it"

**Comment by BDark000** [comment]
> The 60km/h and 100km/h is a great addition, but you don't simply modify existing mod behavior for your own convenience. There are other railway network out there who are designed to run on 160km/h, or 120km/h with this high acceleration rate.
> 
> You're just requesting at least over 80,000 people who downloaded this mod to rework their railway system because "You want it on your network"

For the acceleration thing let's lift the final decision to Jonathan. Compatibility can be considered, but mainly in essential softwares which allow firms to stick to a stable version of software that is able to maintain their daily operations. MTR mod is not the case. 
And honestly the lowered down acceleration rate will not affect the gameplay very much. If you are referring to calculating the distance needed to reduce speed for a lower speed limit, it's once per applicable section, like a sharp curve after a long straight section. I understand it may be painful to re-do them but the effect is limited, since we should be separating a long straight track into many sections like per 500m. And we ought not to give up an enhancement / feature change before fully understanding its benefits and costs. 

For the slightly big change in 160km/h rail it's due to some users saying that 160km/h and 300km/h is having too big difference, also there is no current MTR network (even with HSR counted in) runs at 160km/h. But I'm open to remaining the current speed limit of obsidian and blaze rail connector, as you can perform a trick with platform rail anyway.

**Comment by Kenny-Hui** [comment]
Breaking backward compatibility is fine when you opens up more possibilities and enhancement that the majority would accept, but I don't see how forcibly lowering the acceleration is an enhancement.

It would just make the entire process way slower for maybe a smaller scale network when the people just want to travel from A to B without hassle.

The time you spend on video games are also usually way lower than the time you have in real life, so you would achieve less in the finite time you have. (The train schedule is also going to be messed up as the journey takes longer than before due to the reduced acceleration/deceleration rate).

As for the rail, we are not trying to recreate the MTR Network.
We would've still been stuck on station name poles for every MTR station (Old MTR Mod), but the goal of this mod is to be customizable, while being able to achieve the same thing that was in the mod before. (e.g. replicating MTR network)

160km/h is a very good balance for many, but there's no way to replicate anymore with this PR apart from the platform rail tricks, which is just abusing an unintended feature. Plus if an section is jammed by any chance, the train would be stuck on 20km/h.

I am the realism guy who likes to follow everything in scale, but respect others who are on the opposite side. (IIRC only changing the accel value would also mess up the train sound)

But in both cases (or the entire PR either way) I'll also leave it to Jonafan as he's the mod creator

**Comment by BDark000** [comment]
> Breaking backward compatibility is fine when you opens up more possibilities and enhancement that the majority would accept, but I don't see how forcibly lowering the acceleration is an enhancement.
> 
> It would just make the entire process way slower for maybe a smaller scale network when the people just want to travel from A to B without hassle.
> 
> The time you spend on video games are also usually way lower than the time you have in real life, so you would achieve less in the finite time you have. (The train schedule is also going to be messed up as the journey takes longer than before due to the reduced acceleration/deceleration rate).
> 
> As for the rail, we are not trying to recreate the MTR Network. We would've still been stuck on station name poles for every MTR station (Old MTR Mod), but the goal of this mod is to be customizable, while being able to achieve the same thing that was in the mod before. (e.g. replicating MTR network)
> 
> 160km/h is a very good balance for many, but there's no way to replicate anymore with this PR apart from the platform rail tricks, which is just abusing an unintended feature. Plus if an section is jammed by any chance, the train would be stuck on 20km/h.
> 
> I am the realism guy who likes to follow everything in scale, but respect others who are on the opposite side. (IIRC only changing the accel value would also mess up the train sound)
> 
> But in both cases (or the entire PR either way) I'll also leave it to Jonafan as he's the mod creator

I would change the quartz rail connector to 200 km/h if acceleration rate is unchanged, since generally users are more concerned with the gap between 160 and 300 than 80 and 120. 
Anyway the emerald rail connector can be added first. 

By the way, talking about train sound, it is getting better after decreasing acceleration. And why i get 0.004m tick^-2 (1.6m s^-2) is the result of  calibrating different train sounds into corresponding train speeds. I don't think it's really a mess up, unless you are assigning m-trains to run at 160 km/h. But isn't it already some kind of messing up?

**Comment by BDark000** [comment]
Update: Jonathan agrees with changing the speed of quartz connector to 200 km/h whilst the acceleration rate of all trains will stay at 0.01m / tick^-2

**Comment by kettle-7** [comment]
I do like the reduced acceleration, definitely good because currently the trains accelerate like electric cars, but changing the speed of existing rail connectors should be a no. Instead of having 100kph rails maybe 200 or 240 could be a better idea. Also hate to be the bearer of bad news but you're gonna needa record more train sounds now...

**Pull request merged**
