### PR TITLE
[Models and sounds only]Toei 10-300 Series (10-650F)

### PR DESCRIPTION
**Pull request by ShimajiroOTS**
I don't know how to assemble this train, so only the BB model and sound.
Also, do not delete the text file with the credits in the sound file.
When assembling, please make it the following length.
* 5 Doors (Long)
* 4 Doors (Normal)
* 2 Doors (Mini)

Note that 3 doors and 1 door are not required for creation.

Note: Straps are not installed to prevent LAG. 

10-300_10-650f

### CODE REVIEW

**Comment by ShimajiroOTS** [comment]
Currently, logo marking issues can cause it to look different than the screenshot.

**Comment by kettle-7** [comment]
I can make a resource pack of this...

**Comment by ShimajiroOTS** [comment]
I wanted to do it for preview, but for some reason I can't. And since it also uses sound in the first place, **it cannot be reproduced with a resource pack.**

**Comment by kettle-7** [comment]
hmm the only thing is I'm not sure the Tokyo trains are being added to the mod, I think it was just mtr, nyc subway and under londonground

**Comment by ShimajiroOTS** [comment]
I modeled it based on K-Train, so I think I can use the same method as when I created Small, but even if I open the java file, I don't know how to assemble it at all.

**Comment by jonafanho** [comment]
I think this would be best to be made into a resource pack, as we can't possibly fit all trains around the world into the main mod.

**Pull request closed without merging**
