### PR TITLE
Add ballast rendering

### PR DESCRIPTION
**Pull request by zbx1425**
Adds ballast rendering under slope rails and flat rails, like this, in order to enhance its visual outlook.
image

It is not ready to be merged. There are some functional and lighting problems currently.
I marked a few TODOs in the code to indicate problems that still needs to be resolved.
Due to my poor knowledge on the internals of MTR, It would help if some helps (especially on L74 of RenderRail.java and L353 of Rail.java) can be given.

### CODE REVIEW

**Comment by zbx1425** [comment]
Is there built-in ways to automatically calculate normals for a face to be rendered?

**Comment by zbx1425** [comment]
image
Still can't get the lightings correct.

**Comment by zbx1425** [comment]
image
Fixed most of the other problems, but the lighting is still a bit off.

**Comment by zbx1425** [comment]
image
Fixed the lighting. The reason of the problem is "ENABLE_DIFFUSE_LIGHTING" being wrongly enabled.
AmbientOcclusion can be added later for better outlook.

**Comment by zbx1425** [comment]
Due to difficulties in implementing, I decided not to add ambient occlusion.
I think this PR is ready to be merged now.

---
Currently the ballast is applied only to straight slopes.
I wonder if it should also be applied to flat curves?

**Comment by zbx1425** [comment]
I found the error in the previous code and fixed Ambient Occlusion.
image
Now it works perfectly, and is ready to be merged.

**Comment by jonafanho** [comment]
There are a bunch of merge conflicts, do you mind taking a look at that? Also, I think it'll be good to add that for curves as well, although I can merge in what you have right now (as soon as the conflicts are resolved).

**Pull request closed without merging**
