### PR TITLE
Customisation of Station Name

### PR DESCRIPTION
**Pull request by ZiYueCommentary**
A simple solution for #146 , use shears to display/hide " Station".

### CODE REVIEW

**Comment by jonafanho** [comment]
Sorry about the failing builds due to SFTP, it's not your fault

**Comment by jonafanho** [comment]
However, I would prefer having a separate block for this though

**Comment by ZiYueCommentary** [comment]
> However, I would prefer having a separate block for this though

I think that a little redundancy, because for now, we only need remove "station" from display content.

**Comment by ZiYueCommentary** [comment]
> However, I would prefer having a separate block for this though

I understand your mean now, you prefer have a new block to custom display content.

[My mod](https://github.com/ZiYueCommentary/Tianjin-Metro) already have one block that support custom display content, I will move it to here :D

**Pull request closed without merging**
